{{- if not .Values.auth_existing_secret_name }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "binderhub-container-registry-helper.fullname" . }}
  labels:
    {{- include "binderhub-container-registry-helper.labels" . | nindent 4 }}
type: Opaque
data:
  auth_token: {{ include "binderhub-container-registry-helper.auth_token" . | required "Failed to get binderhub-container-registry-helper.auth_token" | b64enc | quote }}
{{- end }}
