{{- if not .Values.auth_existing_secret_name }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "binderhub-container-registry-helper.fullname" . }}
  labels:
    {{- include "binderhub-container-registry-helper.labels" . | nindent 4 }}
type: Opaque
data:
  auth_token: {{ .Values.auth_token | required "Either .Values.auth_existing_secret_name or .Values.auth_token is required" | b64enc | quote }}
{{- end }}
