name: Go
on:
  push:
  pull_request:

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  # Set to "" to publish container on tags only
  # Set to "<branch-name>" to also publish on every push to <branch-name>
  PUBLISH_BRANCH: ""
  PLATFORMS: linux/amd64,linux/arm64

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - uses: pre-commit/action@v3.0.0

      - uses: actions/setup-go@v4
        with:
          go-version: "1.18.x"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.18.x"

      - name: go build
        run: make build

      - name: go test
        run: make test

  container:
    needs:
      - lint
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        # with:
        #   fetch-depth: 0

      # - name: Get other tags
      #   id: gettags
      #   uses: jupyterhub/action-major-minor-tag-calculator@v2
      #   with:
      #     githubToken: ${{ secrets.GITHUB_TOKEN }}
      #     prefix: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:"

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          flavor: latest=false
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to container registry
        uses: docker/login-action@v2
        if: >
          github.event_name == 'push' &&
          (github.ref == format('refs/heads/{0}', env.PUBLISH_BRANCH) ||
          startsWith(github.ref, 'refs/tags/'))
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push to container registry
        uses: docker/build-push-action@v3
        with:
          # Needed so that .git directory is available to embed version info
          context: .
          platforms: ${{ env.PLATFORMS }}
          # tags: ${{ join(fromJson(steps.gettags.outputs.tags)) }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: >
            ${{
              github.event_name == 'push' &&
              github.ref == format('refs/heads/{0}', env.PUBLISH_BRANCH) ||
              startsWith(github.ref, 'refs/tags/')
            }}
